

name: CI

on:
 
  workflow_call:
  workflow_dispatch:

jobs:
  
  build:
   
    runs-on: windows-latest
   
    steps:
      
      - uses: actions/checkout@v4
      
      - name: echo
        run: echo Hello, world!

